version: 0.0
os: linux
files:
  - source: target/springboot-restful-webservices-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/app
  - source: scripts/
    destination: /home/ec2-user/app/scripts
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 180
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 180
      runas: ec2-user