version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "Building Spring Boot project with Maven"
      - mvn clean install -DskipTests

artifacts:
  files:
    - target/*.jar  # build result jar file
