# k8s/deployment.yaml
# ----------------------------------------------------------------------
# 1. KUBERNETES DEPLOYMENT: Defines your Spring Boot application Pods
# ----------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-deployment
  labels:
    app: springboot-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-microservice
  template:
    metadata:
      labels:
        app: springboot-microservice
    spec:
      containers:
        - name: springboot-app-container
          image: 961581626265.dkr.ecr.ap-south-1.amazonaws.com/springboot-restful-webservices:<PLACEHOLDER_TAG>
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"

---
# ----------------------------------------------------------------------
# 2. KUBERNETES SERVICE: Exposes the Deployment using an AWS Load Balancer
# ----------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service
  labels:
    app: springboot-microservice
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: springboot-microservice